- name: Roboshop Instances Management file
  hosts: local
  connection: local
  vars:
    Instances: ["mongodb", "redis", "mysql", "rabbitmq"]
    image_id: ami-0220d79f3f480ecf5
    action: "terminate"
  tasks:
    - name: Create instances
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        name: "{{ item }}"
        security_group: "shell-robo-common"
        image_id: "{{ image_id }}"
      loop: "{{ Instances }}"
      when: action == "create"

    - name: Terminate instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        state: absent
      loop: "{{ Instances }}"
      when: action == "terminate"